// Generated by gencpp from file project_practice_1/project_practice1Response.msg
// DO NOT EDIT!


#ifndef PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1RESPONSE_H
#define PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_practice_1
{
template <class ContainerAllocator>
struct project_practice1Response_
{
  typedef project_practice1Response_<ContainerAllocator> Type;

  project_practice1Response_()
    : result(false)
    , x(0.0)
    , y(0.0)  {
    }
  project_practice1Response_(const ContainerAllocator& _alloc)
    : result(false)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::project_practice_1::project_practice1Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_practice_1::project_practice1Response_<ContainerAllocator> const> ConstPtr;

}; // struct project_practice1Response_

typedef ::project_practice_1::project_practice1Response_<std::allocator<void> > project_practice1Response;

typedef boost::shared_ptr< ::project_practice_1::project_practice1Response > project_practice1ResponsePtr;
typedef boost::shared_ptr< ::project_practice_1::project_practice1Response const> project_practice1ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_practice_1::project_practice1Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_practice_1::project_practice1Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_practice_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_practice_1::project_practice1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_practice_1::project_practice1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_practice_1::project_practice1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_practice_1::project_practice1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_practice_1::project_practice1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_practice_1::project_practice1Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_practice_1::project_practice1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82f228b68f8b25d23f33219f5773eb3a";
  }

  static const char* value(const ::project_practice_1::project_practice1Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82f228b68f8b25d2ULL;
  static const uint64_t static_value2 = 0x3f33219f5773eb3aULL;
};

template<class ContainerAllocator>
struct DataType< ::project_practice_1::project_practice1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_practice_1/project_practice1Response";
  }

  static const char* value(const ::project_practice_1::project_practice1Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_practice_1::project_practice1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"float64 x\n"
"float64 y\n"
"\n"
;
  }

  static const char* value(const ::project_practice_1::project_practice1Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_practice_1::project_practice1Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct project_practice1Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_practice_1::project_practice1Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_practice_1::project_practice1Response_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1RESPONSE_H
