// Generated by gencpp from file project_practice_1/project_practice1Request.msg
// DO NOT EDIT!


#ifndef PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1REQUEST_H
#define PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_practice_1
{
template <class ContainerAllocator>
struct project_practice1Request_
{
  typedef project_practice1Request_<ContainerAllocator> Type;

  project_practice1Request_()
    : input(0)  {
    }
  project_practice1Request_(const ContainerAllocator& _alloc)
    : input(0)  {
  (void)_alloc;
    }



   typedef int64_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::project_practice_1::project_practice1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_practice_1::project_practice1Request_<ContainerAllocator> const> ConstPtr;

}; // struct project_practice1Request_

typedef ::project_practice_1::project_practice1Request_<std::allocator<void> > project_practice1Request;

typedef boost::shared_ptr< ::project_practice_1::project_practice1Request > project_practice1RequestPtr;
typedef boost::shared_ptr< ::project_practice_1::project_practice1Request const> project_practice1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_practice_1::project_practice1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_practice_1::project_practice1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_practice_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_practice_1::project_practice1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_practice_1::project_practice1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_practice_1::project_practice1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_practice_1::project_practice1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_practice_1::project_practice1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_practice_1::project_practice1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_practice_1::project_practice1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efb1911a9ea9163151d70e4586fa0801";
  }

  static const char* value(const ::project_practice_1::project_practice1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefb1911a9ea91631ULL;
  static const uint64_t static_value2 = 0x51d70e4586fa0801ULL;
};

template<class ContainerAllocator>
struct DataType< ::project_practice_1::project_practice1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_practice_1/project_practice1Request";
  }

  static const char* value(const ::project_practice_1::project_practice1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_practice_1::project_practice1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 input\n"
;
  }

  static const char* value(const ::project_practice_1::project_practice1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_practice_1::project_practice1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct project_practice1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_practice_1::project_practice1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_practice_1::project_practice1Request_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<int64_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1REQUEST_H
