// Generated by gencpp from file project_practice_1/project_practice1.msg
// DO NOT EDIT!


#ifndef PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1_H
#define PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1_H

#include <ros/service_traits.h>


#include <project_practice_1/project_practice1Request.h>
#include <project_practice_1/project_practice1Response.h>


namespace project_practice_1
{

struct project_practice1
{

typedef project_practice1Request Request;
typedef project_practice1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct project_practice1
} // namespace project_practice_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project_practice_1::project_practice1 > {
  static const char* value()
  {
    return "e735d79d25abc25212525470bd97937f";
  }

  static const char* value(const ::project_practice_1::project_practice1&) { return value(); }
};

template<>
struct DataType< ::project_practice_1::project_practice1 > {
  static const char* value()
  {
    return "project_practice_1/project_practice1";
  }

  static const char* value(const ::project_practice_1::project_practice1&) { return value(); }
};


// service_traits::MD5Sum< ::project_practice_1::project_practice1Request> should match 
// service_traits::MD5Sum< ::project_practice_1::project_practice1 > 
template<>
struct MD5Sum< ::project_practice_1::project_practice1Request>
{
  static const char* value()
  {
    return MD5Sum< ::project_practice_1::project_practice1 >::value();
  }
  static const char* value(const ::project_practice_1::project_practice1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_practice_1::project_practice1Request> should match 
// service_traits::DataType< ::project_practice_1::project_practice1 > 
template<>
struct DataType< ::project_practice_1::project_practice1Request>
{
  static const char* value()
  {
    return DataType< ::project_practice_1::project_practice1 >::value();
  }
  static const char* value(const ::project_practice_1::project_practice1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project_practice_1::project_practice1Response> should match 
// service_traits::MD5Sum< ::project_practice_1::project_practice1 > 
template<>
struct MD5Sum< ::project_practice_1::project_practice1Response>
{
  static const char* value()
  {
    return MD5Sum< ::project_practice_1::project_practice1 >::value();
  }
  static const char* value(const ::project_practice_1::project_practice1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_practice_1::project_practice1Response> should match 
// service_traits::DataType< ::project_practice_1::project_practice1 > 
template<>
struct DataType< ::project_practice_1::project_practice1Response>
{
  static const char* value()
  {
    return DataType< ::project_practice_1::project_practice1 >::value();
  }
  static const char* value(const ::project_practice_1::project_practice1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_PRACTICE_1_MESSAGE_PROJECT_PRACTICE1_H
